version: '3.8'

services:
  app:
    build:
      dockerfile: Sistema Backend/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 0000
  db:
    build:
      dockerfile: Base de datos/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    volumes:
      - db-data:/var/lib/postgresql/data


  volumes:
    db-data: